### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by voidcode** [voidcode/Diaspora-Webclient#10]
Bug repport over 13 times,
4 times per week out of 1300 users, 
Via android develper webinterface.

Only one user comment on this bug:
shut down.

---

Exception class java.lang.NullPointerException
Source method MainActivity.onKeyDown()

java.lang.NullPointerException
at com.voidcode.diasporawebclient.MainActivity.onKeyDown(MainActivity.java:229)
at android.view.KeyEvent.dispatch(KeyEvent.java:1257)
at android.app.Activity.dispatchKeyEvent(Activity.java:2075)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1673)
at android.view.ViewRoot.deliverKeyEventToViewHierarchy(ViewRoot.java:2493)
at android.view.ViewRoot.handleFinishedEvent(ViewRoot.java:2463)
at android.view.ViewRoot.handleMessage(ViewRoot.java:1752)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:144)
at android.app.ActivityThread.main(ActivityThread.java:4937)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)

**Comment by voidcode** [comment]
See the fix here: https://github.com/voidcode/Diaspora-Webclient/pull/18
