### ISSUE TITLE
Won't start on Motorola xoom

### ISSUE THREAD

**Issue by voidcode** [voidcode/Diaspora-Webclient#11]
Repport 4 times(ones by email).

Crash: Exception class java.lang.NullPointerException
Source method: MainActivity.isNetworkAvailable()
User message: won't start on Motorola xoom

---

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.voidcode.diasporawebclient/com.voidcode.diasporawebclient.MainActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1815)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1831)
at android.app.ActivityThread.access$500(ActivityThread.java:122)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1024)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:132)
at android.app.ActivityThread.main(ActivityThread.java:4123)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:491)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.voidcode.diasporawebclient.MainActivity.isNetworkAvailable(MainActivity.java:283)
at com.voidcode.diasporawebclient.MainActivity.onCreate(MainActivity.java:43)
at android.app.Activity.performCreate(Activity.java:4397)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1048)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1779)

---

This bug is a new bug v1.5
It seems error came after I added 4G support.

**Comment by voidcode** [comment]
Try to seek help through stackoverflow.com
http://stackoverflow.com/questions/8936403/cant-get-connectivitymanager-to-work-on-motorola-xoomhoneycomb-3-2

**Comment by sedrubal** [comment]
on hammerhead it doesn't start, too. But I haven't looked at the stack trace...
