### ISSUE TITLE
On No wifi or 3G, close button end in error

### ISSUE THREAD

**Issue by voidcode** [voidcode/Diaspora-Webclient#5]
Error on line 16 see: https://github.com/voidcode/Diaspora-Webclient/blob/master/src/com/voidcode/diasporawebclient/SetupInternetActivity.java 

A user reported this:

java.lang.IllegalStateException: Could not find a method onclick_button_close(View) in the activity class com.voidcode.diasporawebclient.MainActivity for onClick handler on view class android.widget.Button with id 'settings_button_close'
at android.view.View$1.onClick(View.java:2147)
at android.view.View.performClick(View.java:2501)
at android.view.View$PerformClick.run(View.java:9107)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3835)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NoSuchMethodException: onclick_button_close
at java.lang.ClassCache.findMethodByName(ClassCache.java:247)
at java.lang.Class.getMethod(Class.java:962)
at android.view.View$1.onClick(View.java:2140)
... 11 more

**Comment by voidcode** [comment]
This bug will be fix in version 1.3

**Comment by voidcode** [comment]
Bugfix is now commit to master branch
